### ISSUE TITLE
Build Problem with Exodus-II & HDF5 built from Spack

### ISSUE THREAD

**Issue by keitat** [NimbleSM/NimbleSM#118] opened 2020-11-05 06:38 UTC
I am trying to install NimbleSM on Cray system at ANL.  Since Seacas/Exodus-II is not installed in the system, I built it using Spack.  Then, the problem is how to resolve find_pacakge and locating headers/libraries (Exodus and HDF5).

I will put all the info later.

**Comment by nmm0** [comment] 2020-11-06 00:04
Duplicate of #119

**Closed by nmm0** 2020-11-06 00:04 UTC
